/*
 * File: app/store/MenuTreeStore.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SmartMenu.store.MenuTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'SmartMenu.model.MenuTreeData',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MenuTreeStore',
            autoLoad: true,
            model: 'SmartMenu.model.MenuTreeData',
            proxy: {
                type: 'ajax',
                url: 'resources/MenuTree.json',
                reader: {
                    type: 'json',
                    rootProperty: 'titles'
                }
            },
            listeners: {
                load: {
                    fn: me.onTreeStoreLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onTreeStoreLoad: function(treestore, records, successful, operation, node, eOpts) {
        var me = this;
        var navBar = Ext.ComponentQuery.query("[reference=navigationToolbar]")[0]; //get view of navigationToolbar;
        var ctrPanel = Ext.ComponentQuery.query("[reference=centerPanel]")[0]; //get view of centerPanel;
        Ext.each(records, function(rec, index){
            console.log("rec: ", rec);
            navBar.add({
                xtype: "button",
                text: rec.data.name,
                listeners: {
                     click: function(){
                            console.log("called: ", rec.data.name);
                            ctrPanel.setHtml("This is "+ rec.data.name + " content");
                     }
                }
            });

        }, this);


    }

});