/*
 * File: app/view/NavigationToolbar.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SmartMenu.view.NavigationToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.navigationtoolbar',

    requires: [
        'SmartMenu.view.NavigationToolbarViewModel',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'navigationtoolbar'
    },
    height: 40,

    items: [
        {
            xtype: 'button',
            margins: '5px',
            text: 'Menu1Btn',
            menu: {
                xtype: 'menu',
                cls: 'topMenu',
                itemId: 'menu1',
                width: 120,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item',
                        menu: {
                            xtype: 'menu',
                            itemId: 'sub1Menu1',
                            width: 120,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item',
                        menu: {
                            xtype: 'menu',
                            itemId: 'sub2Menu1',
                            width: 120,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                }
                            ]
                        }
                    }
                ]
            }
        },
        {
            xtype: 'button',
            text: 'Menu2Btn',
            menu: {
                xtype: 'menu',
                itemId: 'menu2',
                width: 120,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item',
                        menu: {
                            xtype: 'menu',
                            itemId: 'sub1Menu2',
                            width: 120,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    }
                ]
            }
        }
    ]

});